config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'weights/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "weights#index"
  resources :weights, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :weights
end

app/models/weight.rb
class Weight < ApplicationRecord
  def self.chart_date
    order(date: :asc).pluck('date', 'value').to_h
  end
  validates :value, presence: true
  validates :date, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  def index
    @weights = current_user.weights
    @first_weight = @weights.where(date: 1).pluck(:value).to_s
    @progress = @weights.maximum(:date)
    # @newest_weight = @weights.where(id: @weights.maximum(:date)).pluck(:value).to_s
    # @hoge = @newest_weight-@first_weight
  end

  def new
    @weight = Weight.new
  end

  def create
    Weight.create(weight_params)
  end

  def destroy
    weight = Weight.find(params[:id])
    weight.destroy
  end

  private

  def weight_params
    params.require(:weight).permit(:value, :date).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeightRecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Weight-Record</a></h1>
        <div class="user_nav grid-6">
          <a class="post" href="/weights/new">体重を記録する</a>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/weights/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>保存が完了しました。</h3>
    <a class="btn" href="/">マイページへ戻る</a>
  </div>
</div>

app/views/weights/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">マイページへ戻る</a>
  </div>
</div>

app/views/weights/index.html.erb
<div class="contents row">
  <div class="line_chart">
    <%= line_chart @weights.chart_date, width: "90%", height: "500px",label: "体重記録",xtitle: "日付",ytitle: "体重(kg)"%>
  </div>
  <%# <div class="progress">
      <%# <p><%= @progress %>日経過⭐️<%= @newest_weight %>キロ</p> %>
  </div> %>
  <div class="data">
    <% @weights.each do |weight| %>
      <% if user_signed_in? && current_user.id == weight.user_id %>
        <div class="date">
          <p><%= weight.date %>日目</p>
        </div>
        <div class="value">
          <p><%= weight.value %>kg</p>
        </div>
        <div class="destroy">
          <%= link_to '削除', weight_path(weight.id), method: :delete %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/weights/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>体重を保存する</h3>
    <%= form_with(model: @weight, local: true) do |form| %>
      <%= form.text_field :value, placeholder: "体重(kg)" %>
      <%= form.text_field :date, placeholder: "日時(日目)" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>